### ISSUE TITLE
Support Queue timing in Python agent

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_python#120]
Checking the request headers for officially supported frameworks like Django and Flask should be straight forward.

We should also have a generic API interface for recording Queue time in other cases.

**Comment by dlanderson** [comment]
@cschneid Should we make this a layer as a child of the parent span?

**Comment by cschneid** [comment]
I think that will work. The Ruby agent creates a span named: `"QueueTime/Request"`

**Comment by dlanderson** [comment]
@adamchainz Can you look into implementing? You can create a new child span under the span we start in the Django middleware: https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/django/middleware.py#L25

Please also add for Flask, Pyramid, and Bottle.

Here's the headers we look for and how the Ruby agent does it: https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/layer_converters/request_queue_time_converter.rb#L5

**Comment by adamchainz** [comment]
Sure thing!
