### ISSUE TITLE
Fails if settings.BASE_DIR is not set

### ISSUE THREAD

**Issue by ipmb** [scoutapp/scout_apm_python#123]
https://github.com/scoutapp/scout_apm_python/blob/6d805805170580ab8fcab98ce7ad96ac6866325d/src/scout_apm/django/config.py#L15

`BASE_DIR` is not a required Django setting. It may not exist for a project and if it doesn't, the project initialization fails once scout is installed.

**Comment by dlanderson** [comment]
Thank you for the report @ipmb. I've released v1.3.4 with the fix.
