### ISSUE TITLE
Support ignore transactions

### ISSUE THREAD

**Issue by rittersport3** [scoutapp/scout_apm_python#128]
Hi there,

So, we are looking for ways to reduce the total number of transactions in scout... and the sampling solution for ruby was neat and clever. So, any chance of this coming? At least for flask :-).

**Comment by Nihisil** [comment]
Any plans for this?

**Comment by dlanderson** [comment]
This has been released in v2.0.0. You can ignore transactions two ways:

  * The `ignore` configuration option. This is a list of URI paths that will be ignored if they match the path seen in Django, Flask, Bottle, Pyramid.
  * By calling `scout_apm.api.ignore_transaction()` from within your own code.

**Comment by jwicks** [comment]
I had trouble using the `ignore` configuration option. I'm using `Django==1.10.2` and `scout-apm==2.0.1`. I didn't find docs for what setting to use so I assumed `SCOUT_IGNORE`. Here is my settings.py, I tried a lot of options:

```python
SCOUT_IGNORE = ["/healthcheck", "healthcheck", r'^healthcheck']
```

And here is my urls.py:

```python
def healthcheck(request):
    return HttpResponse()

urlpatterns = [
    url(r'^healthcheck', healthcheck),
    ...
]
```

The following by itself ended up working:
```python
def healthcheck(request):
    # suppress this from scout usage/costs
    ignore_transaction()
    return HttpResponse()
```

But I would prefer to use a setting to ignore the paths. What setting should I use?

**Comment by adamchainz** [comment]
Hi,

I’ve started helping with maintenance here but don’t have time to look into this right now as I’m just arriving at Djangocon Europe. I’ll try take a look in a day or two, Dave or someone else might be able to get back to you in the meantime.

Btw your URL conf may be missing a trailing $ there, currently it matches all URL’s starting with ‘healthcheck’, rather than being exact? Maybe it was just in your example though!

Thanks,

Adam

**Comment by dlanderson** [comment]
Hi @jwicks - can you try using the API interface? E.g:

```python
from scout_apm.api import Config
Config.set(ignore=["/healthcheck"])
```

The `SCOUT_IGNORE` env var should work - we'll look into that.

**Comment by jwicks** [comment]
@dlanderson no luck. For reference, here is my `urls.py`:
```python
def healthcheck(request):
    return HttpResponse()

urlpatterns = [
    url(r'^healthcheck/?$', healthcheck),
    ...
]
```

This did not work in `settings.py`:
```python
import scout_apm.api
scout_apm.api.Config.set(ignore=["/healthcheck", "healthcheck"])
scout_apm.api.install()
```

This did not work either:
```python
import scout_apm.api
config = {'ignore': ["/healthcheck", "healthcheck"]}
scout_apm.api.install(config=config)
```

**Comment by dlanderson** [comment]
Ok, looks like we need to investigate @adamchainz 

@jwicks Sorry for the inconvenience. We'll follow up when we know more

**Comment by adamchainz** [comment]
Hi @jwicks ,

It seems this functionality was broken on Django < 1.10. I've released a fix for this in version 2.0.4. Can you let us know if this works for you?

Thanks,

Adam

**Comment by jwicks** [comment]
@adamchainz version 2.0.4 fixed it for me. Thanks!

For reference, here is the config I have working.

`settings.py`:
```python
SCOUT_IGNORE = ["/healthcheck"]
```

`urls.py`:
```python
def healthcheck(request):
    return HttpResponse()

urlpatterns = [
    url(r'^healthcheck/?$', healthcheck),
    ...
]
```

**Comment by nburt** [comment]
I've been trying to ignore health checks as well. We're on version 3.2.1. Per the [FAQ](https://scoutapm.com/docs/python/faq) it looks like an env variable of `SCOUT_IGNORE='/ping/'` should work but they're still coming through

Do we need to set SCOUT_IGNORE in settings.py as well? Or does it need to be in array format?

**Comment by jrothrock** [comment]
Hey @nburt

How are you currently handling environment variables? The `SCOUT_IGNORE='/ping/'` should work (and accepts either a list, string or tuple):
https://github.com/scoutapp/scout_apm_python/blob/b5b7f3af46d92aa18d1a0b35e1f5bc44c6242cb8/src/scout_apm/core/config.py#L334-L351

In the settings.py can you set SCOUT_LOG_LEVEL=debug and set `logging.basicConfig(level='DEBUG')` (or how ever you handle logging)?

You can also use the `Config` interface:
https://scoutapm.com/docs/python/configuration

**Comment by nburt** [comment]
Thanks @jrothrock 

We're deploying using AWS Elastic Container Service and we load the env variables in the task definition from an env file. We also use `python-dotenv` in settings.py:

```
from dotenv import load_dotenv
load_dotenv()
```

I did a little testing with debug log level and both of these did work to prevent it from getting sent:
```
SCOUT_IGNORE=os.environ.get("SCOUT_IGNORE", "")
```
and
```
Config.set(
    ignore=["/ping/"],
)
```
