### ISSUE TITLE
Improve testing by using pytest fixtures

### ISSUE THREAD

**Issue by rsyring** [scoutapp/scout_apm_python#148]
Just FYI, you can improve your testing UX by using pytest fixtures:

Current test:

```python
def test_core_agent_permissions_custom():
    ScoutConfig.set(core_agent_permissions=770)
    config = ScoutConfig()
    try:
        assert 0o770 == config.core_agent_permissions()
    finally:
        ScoutConfig.reset_all()
```

Improved? test:

```python
import pytest

from scout_apm.core.config import ScoutConfig


@pytest.fixture(scope="module")
def reset_config():
    """ Reset the config before each test.  """
    ScoutConfig.reset_all()


def test_core_agent_permissions_custom():
    ScoutConfig.set(core_agent_permissions=770)
    config = ScoutConfig()
    assert 0o770 == config.core_agent_permissions()
```
That way, the test author just worries about the test and the fixture takes care of making sure the config is pristine before each test.

Lots of other options for fixtures: https://docs.pytest.org/en/latest/fixture.html

**Comment by dlanderson** [comment]
Thanks for the suggestion @rsyring ! There's some reasoning behind why we do it this way, at least for certain things: https://github.com/scoutapp/scout_apm_python/blob/a3b223adf99c449d5cca54d5548195ee3bfbc08c/tests/conftest.py#L30

**Comment by rsyring** [comment]
:+1:

**Comment by dlanderson** [comment]
Thanks again @rsyring ! FYI we're expanding into more languages in 2019 and we're looking for someone to help with developing and maintaining `scout_apm_python` - ping us if you're interested !
