### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by michaelpjones176** [scoutapp/scout_apm_python#149]
I'm following Learn Python the Hard Way when I ran into the error said above, I'm using Python 2.7.
`print formatter % (
	'I had this thing.'
	'That you could type up right.'
	"But it didn't sing."
	"So I said goodnight."
)`

**Comment by michaelpjones176** [comment]
It's vertical I swear!

**Comment by cschneid** [comment]
@michaelpjones176 - this repository is for a specific python library, and unfortunately not for general language learning. Are you using the ScoutAPM agent (see [https://scoutapp.com](https://scoutapp.com))?

For learning python, I'd suggest looking at IRC or finding a forum that focuses on beginners.
