### ISSUE TITLE
Add Nameko instrumentation

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_python#16]
Instrument [Nameko](https://github.com/nameko/nameko), a Python framework for building microservices.

**Comment by geoffjukes** [comment]
I'd sign up immediately if you had this :)

**Comment by gpkc** [comment]
Me too.

**Comment by kigen** [comment]
Me too.

**Comment by geoffjukes** [comment]
@itsderek23 I see the Python agent is now GA, with support for several apps. Any thoughts on Nameko now?

**Comment by adamchainz** [comment]
Version 2.4.0 was just released with basic Scout integration with extra data picked up for HTTP services. Future versions can expand to get extra other data from Nameko service types depending on demand :) This included contributing a few small bug fixes to Nameko itself.

Enjoy, let us know how it works!

**Comment by geoffjukes** [comment]
Fantastic @adamchainz ! As promised, I've signed up just to give this a whirl.

The HTTP services we run are a small % of the total Nameko footprint for us.

Instrumenting the RPC service type would be huge for us.

**Comment by adamchainz** [comment]
Hi @geoffjukes 

Sorry my announcement wasn't so clear. *All* service types can be instrumented with the new integration. This will track the service and method as a Scout transaction, capturing any library calls beneath (e.g. SQLAlchemy). Extra context is added only for HTTP services at the moment, such as the user's IP.

I'm sure more context can be tracked for RPC services too, perhaps some RabbitMQ details? Let us know what would be useful to see and we can add it.

Thanks,

Adam

**Comment by geoffjukes** [comment]
Hi @adamchainz 

How would I go about instrumenting a `rpc` service? I've installed scout, and instantiated `ScoutReporter`. The Apps are created in the Scout UI, but only the HTTP service is reporting data.

**Comment by adamchainz** [comment]
Excellent to hear @geoffjukes ! 

I realize I didn't post the docs because they haven't been merged yet, so I guess you found out how to integrate by reading the source - sorry for that. For others' reference, the docs PR is at https://github.com/scoutapp/slate_apm_help/pull/54/files .
