### ISSUE TITLE
IndexError thrown from tracked_request.py

### ISSUE THREAD

**Issue by philipbelesky** [scoutapp/scout_apm_python#21]
Hi,

I've been trying out scout with a django app deployed to heroku. Thus far I've been really enjoying it!

One thing I've noticed on both a staging app and the main app is that shortly after deploying and enabling scout for the first time a number of different views would throw errors, with the stack trace:

```
IndexError: pop from empty list
  File "django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 119, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "scout_apm/core/monkey.py", line 212, in __call__
    return self._eop_wrapper_(self.__subject__, *args, **kwargs)
  File "scout_apm/core/stacktracer.py", line 61, in tracing_function
    TrackedRequest.instance().stop_span()
  File "scout_apm/core/tracked_request.py", line 58, in stop_span
    stopping_span = self.active_spans.pop()
```

These errors don't persist after refresh, and don't seem to be triggered after re-visiting the page. Nor is there any pattern to when they are thrown, except that they no longer seem to throw once the page has refreshed and loaded successfully. So apologies if this is raising an issue that can't be reproduced; I'm happy for this to be closed until/if I can find a means of triggering it reliably.

One complicating factor might be that the app uses [channels](https://github.com/django/channels) and thus the [daphne](https://github.com/django/daphne) webserver and ASGI. Other complicating factors might be that we are using Sentry and Redis for caching.

**Comment by cschneid** [comment]
I'll have to look deeper into this, but here's some background on what the error means, and my initial guess.

We store an object (TrackedRequest) in a thread-local variable, and then call `start_span()` and `stop_span()` on it, as we enter and exit instrumented sections of your code. These calls can nest, with several starts before a stop is ever called.

My guess is that the channels code breaks the 1 request per thread assumption we have in our agent, making those start and stop calls not match up. So at some point, a stop is called where no start happened, resulting in the exception you see.

I changed the title of this issue to test the channel support, with daphne and ASGI. Separately, there will be a change toon to prevent mismatches from ever raising. Unexpected agent state shouldn't 
 cause visible exceptions.

**Comment by philipbelesky** [comment]
Ah great, thanks so much for looking into this. We did note that (once there was a bit more load on the site) the error did seem to be throwing on a consistent but small subset of requests. Channels is a little bit of a niche case but it would be great if this were resolved and we could go back to having scout enabled!

**Comment by jwmayfield** [comment]
I get this same error pretty much constantly if Scout is enabled, and we are not running channels or ASGI.  Django 1.11 on waitress server, Python 3.6, running on Heroku-16 stack.

Sometimes from `scout_apm/core/tracked_request.py in stop_span at line 59`, where it seems to happen consistently during exception handling.

More often from `scout_apm/django/middleware.py in __call__ at line 23`, where it's just happening during normal response processing.

**Comment by dlanderson** [comment]
Thanks for the report @jwmayfield - We'll release an updated version to prevent a span mismatch from raising.

**Comment by dlanderson** [comment]
Version 1.1.5 no longer raises on span mismatch. We will look into underlying cause of span mismatches where it is not expected

**Comment by cschneid** [comment]
Closing this issue, since the exception shouldn't escape now, we will be looking into the underlying mismatches.
