### ISSUE TITLE
Add support for Dramatiq

### ISSUE THREAD

**Issue by matthewhazlehurst** [scoutapp/scout_apm_python#222]
Could we investigate the feasibility of adding support for the Dramatiq background job library?

https://dramatiq.io/

We have only had the one request for it as far as I am aware. But if is not a huge job then it would be beneficial to have going forward.

**Comment by adamchainz** [comment]
Will look into it!

**Comment by adamchainz** [comment]
Version 2.4.0 just released with Dramatiq instrumentation!
