### ISSUE TITLE
Gracefully handle a missing or malformed core download

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#23]
The stack trace in #22 shouldn't ever happen during startup. We should capture and log errors, but not otherwise stop launching of Django (or any other framework).

**Comment by dlanderson** [comment]
Oops, it's an `IOError`, which should be listed on https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/core_agent_manager.py#L203

**Comment by cschneid** [comment]
#24 closed the IOError we were seeing.
