### ISSUE TITLE
Support for Starlette framework

### ISSUE THREAD

**Issue by AgentShir** [scoutapp/scout_apm_python#233]
Had a customer come through who was trying to use Scout on their app: 
![Image 2019-08-23 at 3 19 28 PM](https://user-images.githubusercontent.com/26899691/63626850-bd79ab80-c5b9-11e9-8b8f-140ec76906b5.png)

Customer said that the app is only reporting the 4XX and 5XX responses, not the 2XX

**Comment by adamchainz** [comment]
Will look into it. We don't have any official async support right now and I suspect it's a fair amount of work to add in 🤔

**Comment by adamchainz** [comment]
@AgentShir this was just released in version 2.8.0, can you notify that customer please? Thanks!

**Comment by AgentShir** [comment]
@adamchainz Will do, thank you for your assistance!
