### ISSUE TITLE
Allow configuration of 'hostname'

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#248]
A customer has a setup where all of their servers have the same value for their hostnames. This causes the nodes table in our UI to merge all of their info.

* add a configuration value
* send that to Core Agent at startup.

Then there is a Core Agent task to pass that data along correctly.

**Comment by adamchainz** [comment]
This is already supported. We have the [`hostname` key in config](https://github.com/scoutapp/scout_apm_python/blob/41cf5f682f757df868732601dc700891ff3e4413/src/scout_apm/core/config.py#L66). It's passed to the agent in [AppMetadata](https://github.com/scoutapp/scout_apm_python/blob/41cf5f682f757df868732601dc700891ff3e4413/src/scout_apm/core/metadata.py#L37).

I just tested my Django test app with `SCOUT_HOSTNAME=foobar python app.py runserver` - I could override it and it was passed to the core agent, but it didn't get passed through to Scout as my node name still showed up as my computer name.

I think this only needs core agent changes then?

**Comment by adamchainz** [comment]
Fixed in #251.

**Comment by nMustaki** [comment]
Thanks !
