### ISSUE TITLE
Enable Logging to stdout for Core Agent binary

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#25]
The pre-compiled binary part of our agent is launched by our Python agent, and daemonizes. As part of that process, it disconnects itself from STDOUT (and STDIN and STDERR). The binary defaults to logging to STDOUT, but by the time it starts logging, it doesn't actually have a STDOUT any more.

Find a way to attach to the same STDOUT as the python agent.

This is most relevant on Heroku, where logging to a file is not feasible.

Note: You can set SCOUT_LOG_FILE to set a file to log to.

**Comment by dlanderson** [comment]
Reopening this in the core agent issue tracker
