### ISSUE TITLE
Config value `log_level` does not seem to get applied to the python logging library

### ISSUE THREAD

**Issue by negativetwelve** [scoutapp/scout_apm_python#260]
We have a flask app running the latest 2.5.0 version of Scout APM. I have tried setting the `log_level` via an ENV variable and via the flask app config. Both methods actually set the value properly, but the logging module seems to ignore the value.

Confirmed this when I removed all custom settings, the default value should be `INFO` but we are seeing several `DEBUG` lines from scout in our logs.

I fixed this manually by setting the `log_level` via:

```
import logging

scout_logger = logging.getLogger('scout_apm')
scout_logger.setLevel('INFO')
```

Is this a known issue or am I configuring it improperly?

**Comment by adamchainz** [comment]
Hi @negativetwelve 

It's not well named or explained in the docs but the `log_level` config setting only affects the core agent binary, not the Python library logging. Scout doesn't configure the log level of the `scout_apm` logger at all, so your configuration to change the level is correct.

The documentation [also has some snippets](https://docs.scoutapm.com/#python-logging) that work as a starting point, configuring the logging module to set the level and copy the output to file. Hope they help.

Thanks,

Adam

Will look into improving the documentation on this. Maybe we could also have a different configuration value for configuring the python logging level.

**Comment by negativetwelve** [comment]
Got it, thanks @adamchainz. Configuration value would be great but not a blocker right now. Thanks!

**Comment by adamchainz** [comment]
I think we aren't going to add a setting for this. It's too hard to reliably configure the Python logging module *at the same time* application code can configure it, through `logging.config.dictConfig`, Django's `LOGGING` setting, etc. We [document how to do this](https://docs.scoutapm.com/#python-logging).

The `log_level` setting has been renamed `core_agent_log_level` with extra docs. This should avoid further confusion.
