### ISSUE TITLE
Deprecation warning thrown without using a config

### ISSUE THREAD

**Issue by rik** [scoutapp/scout_apm_python#287]
I'm seeing this deprecation warning even though I have not configured the agent in any way.

```
The config name 'log_level' is deprecated - please use the new name 'core_agent_log_level' instead.
```

**Comment by adamchainz** [comment]
Hi @rik ,

Thanks for the report. Afraid I can't reproduce it here - in a clean environment with 2.6.0 I can only trigger the deprecation warning by overriding.

Configuration can be in a number of sources: environment variable, Django setting, Flask config, where it will be prefixed and uppercased to be `SCOUT_LOG_LEVEL`. Can you check for these? I admit the message could be clearer about these sources and I'll look into improving that.

Thanks,

Adam

**Comment by rik** [comment]
Ah right, it was the environment variables. I forgot to look there because of the magic of Heroku Add-ons. Thanks!

**Comment by adamchainz** [comment]
Glad to help! #288 adds more to that message so it will help others.
