### ISSUE TITLE
Capture details of Celery Chains and Chords

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#36]
Celery has some more advanced features to join multiple jobs into one. The agent needs testing and investigation into how they can be best instrumented.

**Comment by adamchainz** [comment]
After some investigation, I determined the easiest attributes to track are the current task ID and parent task ID. Together they provide a reference point to discover where in a chain, chord, group, etc. the current task is, by checking against the results backend.

The `group` and `chord` could also be tagged but it might be too much extra context data to push into Scout? https://docs.celeryproject.org/en/latest/userguide/tasks.html#task-request . Happy to add them if they would be useful though.
