### ISSUE TITLE
Add Huey integration

### ISSUE THREAD

**Issue by adamchainz** [scoutapp/scout_apm_python#362]
[Huey](https://huey.readthedocs.io/en/latest/) is a relatively popular task queue, and we've had at least one enquiry for it. We should support it.

**Comment by adamchainz** [comment]
Since it's gevent driven, we'd also have to  add official support with #28.

**Comment by cburza** [comment]
@adamchainz You can run Huey with processes, threads or greenlets. We hanven't run it with greenlet, so would be great to have a version that works with processes or threads.

**Comment by adamchainz** [comment]
Ah right. Will look into it then :)
