### ISSUE TITLE
Capture N+1 Tracebacks

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#37]
Background: Capturing and processing Tracebacks is expensive enough that we can't do it all the time.

Our Ruby agent keeps track of how many times a given section of instrumented code is called, and if it happens enough, captures a backtrace. This is handy for SQL calls that are individually fast enough not to trip our threshold to capture a traceback, but happen so many times that it's important to get it.

We need to implement something like this in this Python agent.

**Comment by dlanderson** [comment]
Added in v1.1.8
