### ISSUE TITLE
Instrument rq

### ISSUE THREAD

**Issue by adamchainz** [scoutapp/scout_apm_python#370]
RQ is a popular task queue: https://python-rq.org/

We should have an integration just like we do other task queues.

**Comment by matthewchigira** [comment]
We had a request to add support for Django RQ: https://github.com/rq/django-rq

**Comment by adamchainz** [comment]
I've just released version 2.9.0 which includes the RQ integration https://github.com/scoutapp/scout_apm_python/blob/master/CHANGELOG.md#290-2019-11-29

The doc updates are this PR : https://github.com/scoutapp/slate_apm_help/pull/70/files .
