### ISSUE TITLE
AttributeError: 'list' object has no attribute 'clear'

### ISSUE THREAD

**Issue by babu-upcomer** [scoutapp/scout_apm_python#38]
Attaching the screenshot of stack trace,

![capture](https://user-images.githubusercontent.com/19949828/40408463-3814f2fc-5e85-11e8-94d9-a729fdcb3488.PNG)

Running Python 2.7 and Django 1.11 on uWSGI + gevent cores.

**Comment by cschneid** [comment]
#57 closed this.
