### ISSUE TITLE
Huey Django integration

### ISSUE THREAD

**Issue by cburza** [scoutapp/scout_apm_python#391]
Thank so much for adding Huey integration (#362). When using Django the Huey task worker is started with a management command which is part of the Huey package. We are unable to modify the managements command. I suggest that a Django app is added to Scout which will connect to the Huey signals during the Django startup process.

**Comment by adamchainz** [comment]
Hi @cburza ,

It looks like you can set [`HUEY` in your Django settings](https://huey.readthedocs.io/en/latest/django.html) to a `Huey()` instance. If you do this, you should be able to call `attach_scout` on that instance, and the integration should work. You can configure Scout through your Django settings.

I'll look into testing this further and adding a documentation change if nothing else.

Thanks,

Adam

**Comment by adamchainz** [comment]
@cburza I've just given this a test and it looks harder than I thought. Our `attach_scout` function will only work in a Django-less Huey setup. I will look into adding a Django-startup-patch-huey function as you suggested.

**Comment by adamchainz** [comment]
Hi @cburza

I've just released version 2.9.0 which includes Django-Huey support: https://github.com/scoutapp/scout_apm_python/blob/master/CHANGELOG.md#290-2019-11-29

I've tested it with a mini Django + Huey app which you can see at https://github.com/adamchainz/scout-test-apps/tree/master/django-huey

The doc updates are this PR : https://github.com/scoutapp/slate_apm_help/pull/72/files. However the main gist of it is that your Huey instance will be automatically instrumented if you have the Django integration installed.

Thanks,

Adam
