### ISSUE TITLE
GitHub-compatible backtraces

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_python#47]
Currently we send up the full path w/each frame in the backtrace. This means we can't fetch file contents and git blame data for in-app code as we don't erase the portions of the path outside the base directory of the app.

In this case, if we found frames that included `settings.BASE_DIR`, which is `/Users/dlite/projects/play/wagtail_demo_site`, then removed that portion of the path, we'd be able to fetch the code:

`/Users/dlite/projects/play/wagtail_demo_site/search/views.py` => `/search/views.py`

![image](https://user-images.githubusercontent.com/7880/41004052-c815cfca-68d5-11e8-8f5e-8c6b7a925df3.png)

**Comment by cschneid** [comment]
This is in the core-agent's next release.

**Comment by itsderek23** [comment]
I've verified this works w/the core agent.

We'll want to address #93 before releasing.
