### ISSUE TITLE
Add a "flush background thread" function

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#473]
To support one-off cron tasks that exit python when finished, we need to allow the background thread to finish its work. Currently, if the main thread exits, any in-flight data the background thread has is lost.

We should add a `flush_sync` or similar function that blocks until the background thread has sent whatever payloads it has over to the core agent.

**Comment by adamchainz** [comment]
I guess we should by default run this [atexit](https://docs.python.org/3/library/atexit.html?highlight=atexit#module-atexit)

**Comment by cschneid** [comment]
It's ok if it's an opt-in call. But yes it needs a timeout.
