### ISSUE TITLE
Add support for Pyramid instrumentation

### ISSUE THREAD

**Issue by damjankuznar** [scoutapp/scout_apm_python#48]
Please add support for [Pyramid](https://trypyramid.com/) web framework to Scout, similar to Django's.

**Comment by cschneid** [comment]
@damjankuznar - I just pushed #58 for some initial Pyramid support. Can you give it a try locally, and give us any feedback you may have. Then I'll get it merged and released.

Thanks!

**Comment by dlanderson** [comment]
Initial Pyramid support added in v1.1.8
