### ISSUE TITLE
Document Django support for request queueing

### ISSUE THREAD

**Issue by sjamaan** [scoutapp/scout_apm_python#509]
This would be very useful to have and it doesn't seem like a difficult thing to do; just read out the custom X-Request-Start header value from the request object.

**Comment by sjamaan** [comment]
I just noticed this feature already exists! It's just not documented, as far as I can tell. Please add it, as this is quite useful!

**Comment by adamchainz** [comment]
Hi @sjamaan 

Thank you for the report. Yes we support request queuing, and the custom AWS header for it too. The documentation existed for Ruby: https://docs.scoutapm.com/#request-queuing

I've made a PR to our docs to make it language agnostic, with a link from Python: https://github.com/scoutapp/slate_apm_help/pull/99 

Thanks for pointing this out,

Adam
