### ISSUE TITLE
Allow several taggings with the same key

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#51]
A new feature of the CoreAgent is to allow multiple tags with the same key.

Adjust Span in tracked_request.py to support that (several tags, and add a timestamp to each). Then adjust the Command code to be sure that the timestamp is passed through.

**Comment by adamchainz** [comment]
@cschneid what's the value of multiple tagging?

**Comment by cschneid** [comment]
Low for now. Down the line, we'll likely we'll borrow the concept of a `Log` from OpenTracing, which is effectively a point-in-time tag, and leave SpanTag and RequestTag as a once-only value.
