### ISSUE TITLE
Clean library/frameworks from backtraces

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_python#514]
We should clean all non-user code from backtraces as much as possible.  Here's a heroku app running 2.13.0:

<img width="890" alt="Screenshot 2020-04-13 14 39 56" src="https://user-images.githubusercontent.com/102774/79160522-26a36e80-7d97-11ea-8376-f8dfcfd6ece0.png">

**Comment by adamchainz** [comment]
I believe this is what #416 would do. Currently we don't derive `application_root` for any frameworks except Django, and even then not in every case.

I'm not sure `application_root` is always easy to determine. Python apps come in all shapes and folder layouts. But it should be more accurate to do the opposite and filter out/de-emphasize non-app code with the heuristic that if it has `site-packages` in its file path, as that should mean it's installed from elsewhere.

I'll look into it.

**Comment by dlanderson** [comment]
@adamchainz Mind taking another look at filtering these? I think it'd be good to filter anything that contains `/site-packages/`?

**Comment by tim-schilling** [comment]
@dlanderson Do we need the ability to disable this or include specific packages?

**Comment by dlanderson** [comment]
> Do we need the ability to disable this or include specific packages?

No, I don't think we need that ability at this time.
