### ISSUE TITLE
Traces missing Controller spans

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_python#54]
Using `scout-apm` with the Core Agent `trace_reporter` branch, I'm seeing a number of traces w/o `Controller` spans, which is unexpected. 

An example: https://gist.github.com/itsderek23/207d51caaa4cc98841246ffae015f2ec

**Comment by cschneid** [comment]
The current experimental trace capture code doesn't filter on "real requests". So if the instrumented Django code executes some SQL or other code with instruments during initialization, we capture a "trace" for it, even though it's not an actual Web or Job trace.

The existing reporting ("BatchedReporter") does do that kind of filtering.

**Comment by cschneid** [comment]
Looking a bit closer, the trace you link isn't quite what I described (although that happens as well). 
 This one captured our Django Middleware Span, which we insert as the outermost middleware (entered first, exited last), then some SQL was run, but our View middleware was never hit (which we call `Controller` spans). 

So in this case, I think the request came in, and was returned from early by a middleware.
