### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/tmp/scout_apm_core/scout_apm_core-v1.2.9-x86_64-unknown-linux-gnu/core-agent'

### ISSUE THREAD

**Issue by oppianmatt** [scoutapp/scout_apm_python#541]
Seeing this in our logs when trying to use scout.

also

```
/tmp/scout_apm_core/scout_apm_core-v1.2.9-x86_64-unknown-linux-gnu/core-agent start --daemonize true --log-level info --socket /tmp/scout_apm_core/scout_apm_core-v1.2.9-x86_64-unknown-linux-gnu/scout-agent.sock
```

I believe our issue is that we mount /tmp as tmpfs inside a docker and so doesn't have execute capabilites

How do we configure the location of this?

**Comment by oppianmatt** [comment]
this is the issue from docker https://github.com/moby/moby/issues/35890

**Comment by adamchainz** [comment]
Thanks for the detailed report.

You can set the `core_agent_dir` setting to another path of your choosing: https://docs.scoutapm.com/#core_agent_dir-1

I don't think we want to move away from `/tmp` as the default since it's normally reliable.

**Comment by oppianmatt** [comment]
thanks for the answer. I tried keeping it as tmp by changing the mount from a tmpfs mount to a volume mount that is a tmpfs like in this SO https://stackoverflow.com/a/45759927/69949

That got me a bit further. It seems to be reporting now but I did get some other errors in the console:

**Comment by adamchainz** [comment]
Great, glad you got it working.

And yes, some of our log messages could do with copy improvements to show they're normal and okay.
