### ISSUE TITLE
scout breaks caching for django

### ISSUE THREAD

**Issue by oppianmatt** [scoutapp/scout_apm_python#544]
We gave scout a try and looked promising but then we quickly had to disable it on production.

Issue is that scout is adding a `Vary: Cookie` header which breaks caching

This normally happens when some code in django accesses the request.user object. I'm assuming scout is trying to add some meta data and accesses it causing this issue.

We've run into this problem ourselves in the past and the way around is it to look for the internal cached user on the request object. Like this:

```
    # going request.user will generate cookie vary headers, but since
    # we aren't changing the output based on this we want to see the user
    # without adding the header, so look for the lazy user
    if request and hasattr(request, '_cached_user'):
        # noinspection PyProtectedMember
        user = request._cached_user
```

I think if replaced the check for user here

https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/django/middleware.py#L139

**Comment by adamchainz** [comment]
Fix released in version 2.15.2, thanks for the report and PR.
