### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by ausinha** [scoutapp/scout_apm_python#59]
I get this error on the sitemap pages. Here is the rollbar stack trace:

![screen shot 2018-06-18 at 1 13 56 pm](https://user-images.githubusercontent.com/359261/41551332-79f48c90-72f9-11e8-940d-e2662fabe215.png)

**Comment by cschneid** [comment]
@ausinha - if you're not on 1.1.7, can you upgrade Scout? We've fixed a number of issues, including one that resulted in this error.

Beyond that, can you describe anything "interesting" your app may be doing? Async, channels, threading, etc.

**Comment by ausinha** [comment]
Upgrading works!

**Comment by dlanderson** [comment]
Great! Closing - issue fixed in 1.1.7
