### ISSUE TITLE
Investigate removal of X-Amzn-Trace-Id for queuetime

### ISSUE THREAD

**Issue by jrothrock** [scoutapp/scout_apm_python#631]
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

The X-Amzn-Trace-Id header that Amazon adds to ELB only gives time  since epoch in seconds as opposed to milliseconds. This isn't a very accurate measurement, and seems to impact apps negatively (reporting times incorrectly, which seems to be a lot more pronounced since their recent change to hex decimal timestamps)

Whether Amazon is truncating the time or rounding the time to the second may need to be investigated, but either way unless queuetime is above a second this measurement doesn't add much value

**Comment by tim-schilling** [comment]
Good morning Jack. It looks like the header for the request is only going to have seconds. I could imagine them changing it to be a hexadecimal value to do milliseconds in the future, but I can't find any roadmap that would indicate as such. I agree that the appropriate measure is to remove this.

**Comment by tim-schilling** [comment]
Here's a amazon forum post requesting the feature that we'd need to restore this: https://forums.aws.amazon.com/thread.jspa?threadID=333252
