### ISSUE TITLE
When span limit is reached, still send the collected data

### ISSUE THREAD

**Issue by tim-schilling** [scoutapp/scout_apm_python#643]
As per comment [here](https://github.com/scoutapp/scout_apm_python/pull/491#issuecomment-593577188) we should be sending the partially collected data. There's been reports that we've ignored the request when the limit is reached.

**Comment by jrothrock** [comment]
Closing, wasn't able to reproduce. 

I was able to report both Django requests that were over 1500 span limits as well as Celery tasks that were over 1500 spans

**Comment by grace-kuo** [comment]
@grace-kuo
