### ISSUE TITLE
Track when an exception occurs in a Celery task

### ISSUE THREAD

**Issue by jrothrock** [scoutapp/scout_apm_python#649]
Similar to how we do this in other libraries
`tracked_request.tag("error", "true")`

**Comment by tim-schilling** [comment]
I'll need to check how [`task_failure` signal](https://docs.celeryproject.org/en/stable/userguide/signals.html?highlight=task_postrun#task-failure) completes in comparison to `task_postrun`. Though we might be able to key off of postrun's `state` parameter.
