### ISSUE TITLE
Clarify in quickstart instructions for Flask what `db` is

### ISSUE THREAD

**Issue by rsyring** [scoutapp/scout_apm_python#68]
Your current quickstart instructions:

* project readme
* https://apm.scoutapp.com/apps/new?lang=flask
* http://help.apm.scoutapp.com/#flask-installation

Have the following snippet:

```python
from scout_apm.flask import ScoutApm
from scout_apm.flask.sqlalchemy import instrument_sqlalchemy

# Setup a flask 'app' as normal

## Attaches ScoutApm to the Flask App
ScoutApm(app)

## Instrument the SQLAlchemy handle
instrument_sqlalchemy(db)

# Scout settings
app.config['SCOUT_MONITOR'] = True
app.config['SCOUT_KEY']     = "[AVAILABLE IN THE SCOUT UI]"
app.config['SCOUT_NAME']    = "A FRIENDLY NAME FOR YOUR APP"
```

But at this line:

```python
## Instrument the SQLAlchemy handle
instrument_sqlalchemy(db)
```

I'm not sure what `db` is supposed to be.

**Comment by cschneid** [comment]
I'll make a proper change for this tomorrow - but it's the SQLAlchemy object

```
from flask_sqlalchemy import SQLAlchemy

# Attaches SQLAlchemy to the Flask app (return handle into db var)
db = SQLAlchemy(app)
```

**Comment by itsderek23** [comment]
Thanks @rsyring - I've attempted to clarify this in the docs:

![image](https://user-images.githubusercontent.com/7880/41872612-a32a884a-787f-11e8-9907-230e75d200d1.png)

Docs: https://github.com/scoutapp/slate_apm_help/commit/b924aa2a6304ef1d235ed5fdd3daab5c116d0902
