### ISSUE TITLE
Verify traces that exceed 60 seconds are collected

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_python#69]
We're collecting aggregate metrics on transactions that exceed 60 seconds, but we should also verify that we're recording traces that exceed this threshold. 

The core agent reports data every minute, so it's possible there is an edge case around traces that exceed this duration.

This is most likely to occur in Celery Tasks, which are more likely to long-running than a web request.

**Comment by dlanderson** [comment]
Works in a flask app that sleeps for 80 seconds before rendering:

<img width="1579" alt="screenshot 2018-07-30 10 38 19" src="https://user-images.githubusercontent.com/102774/43410644-d49f3616-93e4-11e8-8964-4f821a4fb83b.png">
