### ISSUE TITLE
set /tmp/scout_apm_core directory perms from config

### ISSUE THREAD

**Issue by rsyring** [scoutapp/scout_apm_python#72]
Right now, directory permissions are set with:

https://github.com/scoutapp/scout_apm_python/blob/cab4f2218cfada275a45c355269e61a8945fa581/src/scout_apm/core/core_agent_manager.py#L144

Which obviously results in `700` perms on `/tmp/scout_apm_core/*`.

In my setup, this ends up requiring `root` to clear these files.  If I could set the perms to `770` from a configuration option, it would make it a lot easier to clear these files out.

**Comment by dlanderson** [comment]
@rsyring - Can you describe how your app is configured to start? Ideally scout would be launched only when a python app has been launched as the final, unprivileged user.

**Comment by rsyring** [comment]
When we have an application running in production, the app runs under a user account that has very limited privileges and can not write to application source files.  We also then have a user that can deploy new source code changes, restart the app, etc.  But that user is also limited, it's not a root account.

As an example, for project "foo" we would have two users and a shared group:

* `foo`: the OS user devs SSH in with and the user our deployment scripts work with
* `foo-app`: the OS user that the application runs under (including scout's APM code/binary)
* both users above are a part of the `foo` OS group

So, if the application creates files under `/tmp/scout_apm_core` that are owned by `foo-app` with `700` perms, our `foo` user can't manage those files.  That means I need a devops person who has root access to clear out Scout APM binary files, which means I can't automate that workflow.

If I could configure scout to use `770` perms instead, then my `foo` user can clear out those files because it's in the same OS group `foo`.

HTH clarify what my problem is.

**Comment by dlanderson** [comment]
@rsyring - my hesitation to making it configurable is accidental incorrect permissions due to a misconfiguration or any potential bug in determining the mode from the config.

I'm wondering if this workflow would be an option for you: We provide a command-line interface `core-agent-manager` when the `scout_apm` package is installed. As part of your deploy process, you can call `core-agent-manager download` and then `chmod -R 770 /tmp/scout_apm_core` (and/or chown, etc) to explicitly configure the permissions. Thoughts?

**Comment by rsyring** [comment]
@dlanderson Thanks for your thoughts on this issue.

I'd leave the default permissions as you have them, so unless an app developer makes an explicit decision to override the perms, it should be the same level of security as what you have currently IMO.  If they do make that decision, aren't the security implications on them.  Presumably, we are talking about app developers who would make this change, so they have a lot of power already in the application.

Regarding misconfiguration, in your config example, use:

```python
# If setting, use octal notation, this gets fed directly to os.mkdir's `mode` parameter.
# app.config['SCOUT_TMP_FILE_PERMS'] = 0o700  # default value shown
```
And it's on the app dev if they manage to mess that up, right?

> I'm wondering if this workflow would be an option for you: We provide a command-line interface core-agent-manager when the scout_apm package is installed. As part of your deploy process, you can call core-agent-manager download and then chmod -R 770 /tmp/scout_apm_core (and/or chown, etc) to explicitly configure the permissions. Thoughts?

I can actually do this.  But I'd have to do it on every deploy, which doesn't seem ideal.  Would that potentially upgrade the binary even without the python package version changing?

I'm happy to have a work around but I'm not sure I share your concern about the config option.  Having a config value for files written by an application is a very common paradigm used by lots of libraries/tools.  E.g.: https://docs.djangoproject.com/en/2.0/ref/settings/#file-upload-permissions

**Comment by avelis** [comment]
@dlanderson I also want to second what @rsyring Is advocating for here. It's a little frustrating that this tool out of the box does not "just work". Even with `SCOUT_SOCKET_PATH` the non-configurable default permissions seems like a bit of a glaring omission.

Is this issue open for PR's? Not sure how I would unit test it though.

**Comment by dlanderson** [comment]
Thanks @rsyring and @avelis for your comments.We'll be making the file permissions configurable in an upcoming release.

Do either of you happen to know how the actual python application are being executed as `root`? Usually a web server will start as `root` in order to bind privileged ports, then execute the actual application as a non-privileged user. Just trying to figure out the execution flow in your cases.

**Comment by rsyring** [comment]
@dlanderson thanks for addressing this issue.  To be clear, my applications do not execute as root.  Please see [my comment above](https://github.com/scoutapp/scout_apm_python/issues/72#issuecomment-405689753) for clarity on how our app users are setup.  If you have questions about that setup, just let me know.

**Comment by dlanderson** [comment]
Sorry @rsyring - thanks for reminding me!

**Comment by avelis** [comment]
@dlanderson Our application doesn't run under root. Mostly as a general security best practice.

**Comment by dlanderson** [comment]
@avelis I might be confused. I replied to your email as well. We can investigate further there.

In any case, the mode will be configurable when #147 gets merged and released in a new version. I'll follow up when it's released

**Comment by avelis** [comment]
@dlanderson Looks like I am still running into the permissions issue since `os.makedir()` honors the `umask` of the current process. The SO issue highlights a potential solution. YMMV
https://stackoverflow.com/a/23704144/153262

**Comment by rsyring** [comment]
IMO, changing the umask in the application would be the wrong approach.  You should be able to control umask at the process level.  In our case, we set it in `.profile` and/or uwsgi.
