### ISSUE TITLE
Add LOG_PAYLOAD_CONTENT configuration

### ISSUE THREAD

**Issue by jrothrock** [scoutapp/scout_apm_python#724]
When this configuration is set to true, we will log the payload that is sent to core-agent

This will create parity with the PHP agent:
https://github.com/scoutapp/scout-apm-php/blob/master/src/Agent.php#L497-L503

**Comment by tim-schilling** [comment]
@jrothrock For the case when `LOG_PAYLOAD_CONTENT` is false, should this log anything? I notice that the php agent does. It also includes the number of spans, but that count is already logged in the python agent.

**Comment by tim-schilling** [comment]
Never mind. I see there's already a log for when a batched command is sent over the wire. I'll add in the payload to that message when applicable.
