### ISSUE TITLE
new vertion 2.26 No module named 'elasticsearch' 

### ISSUE THREAD

**Issue by MrSalman333** [scoutapp/scout_apm_python#744]
after updating to scout-apm to 2.26

we got ModuleNotFoundError: No module named 'elasticsearch'

should be easy to fix ,, good luck ^_^

**Comment by tim-schilling** [comment]
Thanks for the report @MrSalman333. Can you share the full stacktrace?

**Comment by tim-schilling** [comment]
Never mind, found it.

**Comment by MrSalman333** [comment]
good

**Comment by tim-schilling** [comment]
@MrSalman333 this is being released now. It should be available in a bit.
