### ISSUE TITLE
Broken with urllib3

### ISSUE THREAD

**Issue by 09F911029D74E35BD84156C5635688C0** [scoutapp/scout_apm_python#751]
urllib3 >= 2.0 causes breakage

![image](https://github.com/scoutapp/scout_apm_python/assets/62552264/cccc3cab-c863-4d71-966e-fb38d480644f)

In new version `HTTPConnectionPool` no longer has private function `_absolute_url`.

**Comment by tim-schilling** [comment]
Thank you for reporting this. We are looking into it.

**Comment by lancetarn** [comment]
Fixed in 3.0.0 release.
