### ISSUE TITLE
PyMongo calls named incorrectly in UI

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_python#80]
In 1.2.0, for PyMongo instrumented calls, the UI shows the method twice:

![screenshot 2018-07-19 09 40 47](https://user-images.githubusercontent.com/102774/42953541-e7cc756a-8b37-11e8-8cc0-251257613d0e.png)

**Comment by itsderek23** [comment]
Another example:

![image](https://user-images.githubusercontent.com/7880/43013410-1219f33c-8c06-11e8-9a28-7f2fdac29b5c.png)

**Comment by itsderek23** [comment]
This is a server-side issue. Raw metric names for the trace:

```
["Middleware/", "MongoDB/InsertOne", "MongoDB/Count", "Controller/all", "Controller/hello.views.mongo", "MongoDB/FindOne", "MongoDB/all", "Middleware/all"]
```

**Comment by itsderek23** [comment]
The formatting is broken as we don't have a collection name (ie `MongoDB/Post/InsertOne`). 

I've adjusted formatting so it is displayed correctly, w/o this, but it would be nice to display the collection name.

**Comment by itsderek23** [comment]
Updated:

![image](https://user-images.githubusercontent.com/7880/43021018-62cc7c64-8c1f-11e8-9d03-85ef044c3421.png)
