### ISSUE TITLE
HTTP calls in traces are missing the URL requested

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_python#82]
For example:

![image](https://user-images.githubusercontent.com/7880/42956277-d096541a-8b3c-11e8-8baa-d255ffecadfa.png)

@dlanderson added this:

![image](https://user-images.githubusercontent.com/7880/42956319-f5759142-8b3c-11e8-8b50-d042878dbce1.png)

...but doesn't appear in traces.

**Comment by dlanderson** [comment]
For SQL, a special tag of 'db.statement' is used for the description field. We need to decide on how we find the description field for different span types in the core agent.

**Comment by cschneid** [comment]
This is in the next release of the core-agent
