### ISSUE TITLE
Display errors panel

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_python#86]
We don't display the errors panel for Python apps. We should.

![image](https://user-images.githubusercontent.com/7880/43013571-9076ef82-8c06-11e8-8bc4-c4f91e01d539.png)

**Comment by cschneid** [comment]
We capture and send that value, at least on the Django environments.

https://github.com/scoutapp/apm/pull/1034 will toggle the server-side display.

**Comment by dlanderson** [comment]
Deployed.
