### ISSUE TITLE
Remove library frames from backtraces

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_python#93]
Currently we send up library frames w/backtraces. This is different than our Ruby agent and causes issues in the backtrace display (can't expand to view library code):

![image](https://user-images.githubusercontent.com/7880/43343790-caea05a2-91a4-11e8-9366-51737eee4c47.png)

Only send up in-app frames.

**Comment by cschneid** [comment]
I've made a change to the CoreAgent to cut out non-app libraries, needs testing.

**Comment by itsderek23** [comment]
Tested. It works!

![image](https://user-images.githubusercontent.com/7880/43406146-dcab966c-93d8-11e8-9993-6a83d276841c.png)
